# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e5c0be84ec55b69f4c68bcfa3bd69002ff43e2d83fb1388a61583e697afd66e1868f6696b99452bb4fd50e2be462055871e3c6a64ad17fe106f1b16b406c5cd

test:
  secret_key_base: 97530cbc385a80ae2f136701bd529c9893a6ebf20fbcf80fcd22f570f1f2f844bfe5706b67bf3cc2e96ac28d8b00753a4da5ca4459ae8d313b1362e7798856ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
